server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://xiyoulinux.org:3306/dd_sign_info?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: xy_xiyoulinux_2017
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.94.135.164
    port: 6379
  http:
    encoding:
      force: true







